// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __TimedPose3DQuaternion_hh__
#define __TimedPose3DQuaternion_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_TimedPose3DQuaternion
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_TimedPose3DQuaternion
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_TimedPose3DQuaternion
#endif



#ifndef __BasicDataType_hh_EXTERNAL_GUARD__
#define __BasicDataType_hh_EXTERNAL_GUARD__
#include "BasicDataType.hh"
#endif
#ifndef __ExtendedDataTypes_hh_EXTERNAL_GUARD__
#define __ExtendedDataTypes_hh_EXTERNAL_GUARD__
#include "ExtendedDataTypes.hh"
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE RTC

_CORBA_MODULE_BEG

  struct TimedPose3DQuaternion {
    typedef _CORBA_ConstrType_Fix_Var<TimedPose3DQuaternion> _var_type;

    
    Time tm;

    RTC::Point3D point3D;

    RTC::Quaternion quaternion;

  

    void operator>>= (cdrStream &) const;
    void operator<<= (cdrStream &);
  };

  typedef TimedPose3DQuaternion::_var_type TimedPose3DQuaternion_var;

  typedef TimedPose3DQuaternion& TimedPose3DQuaternion_out;

  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_TimedPose3DQuaternion;

_CORBA_MODULE_END



_CORBA_MODULE POA_RTC
_CORBA_MODULE_BEG

_CORBA_MODULE_END



_CORBA_MODULE OBV_RTC
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

extern void operator<<=(::CORBA::Any& _a, const RTC::TimedPose3DQuaternion& _s);
extern void operator<<=(::CORBA::Any& _a, RTC::TimedPose3DQuaternion* _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, RTC::TimedPose3DQuaternion*& _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const RTC::TimedPose3DQuaternion*& _sp);





#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_TimedPose3DQuaternion
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_TimedPose3DQuaternion
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_TimedPose3DQuaternion
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_TimedPose3DQuaternion
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_TimedPose3DQuaternion
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_TimedPose3DQuaternion
#endif

#endif  // __TimedPose3DQuaternion_hh__

