// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "TimedPose3DQuaternion.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



void
RTC::TimedPose3DQuaternion::operator>>= (cdrStream &_n) const
{
  (const Time&) tm >>= _n;
  (const RTC::Point3D&) point3D >>= _n;
  (const RTC::Quaternion&) quaternion >>= _n;

}

void
RTC::TimedPose3DQuaternion::operator<<= (cdrStream &_n)
{
  (Time&)tm <<= _n;
  (RTC::Point3D&)point3D <<= _n;
  (RTC::Quaternion&)quaternion <<= _n;

}

